### ISSUE TITLE
Redirect if declined

### ISSUE THREAD

**Issue by noxish** [BytexDigital/BytexDigital.Blazor.Components.CookieConsent#14]
Hi is it possible to redirect user to his homepage if he declined the cookie consent?

**Comment by RyanTT** [comment]
Hi, sorry at the moment I don't think theres any way to achieve that. Do you have non-necessary cookies that the user MUST agree to to use your website?

**Comment by noxish** [comment]
Thank you for your feedback, I was just asked if it was possible.
I said the exact same thing :-P

**Comment by RyanTT** [comment]
What you want to do is technically possible, since you can easily subscribe to the eventhandler that notifies you if the cookie preferences have changed and check if all your wanted categories have been given permission. But the blocking of all content would need to be done by you, probably by hiding all content inside a layout file that then does the necessary checks.
