### ISSUE TITLE
Revoke consent manually seems not to disable services

### ISSUE THREAD

**Issue by OWGS** [BytexDigital/BytexDigital.Blazor.Components.CookieConsent#24]
When a user manually revoke given consent via the preferences modal dialog (e.g. the google analytics service), the service seems not to be disabled.
The type of the script remains "text/javascript instead of changing back to "text/plain"
So I guess the consent remains until the user reloads the page.
Is this the expected behaviour or is this some kind of bug?

**Comment by RyanTT** [comment]
Hi, at the time this is expected behaviour as we have no means to stop the execution of the started scripts that are loaded into the page via script tags. 

To handle this scenario, you would need to subscribe to the event for updated cookie preferences and detect whether Google Analytics has been disabled and reload the page entirely to stop script execution.

In theory, you should be able to achieve this by keeping a reference to the last known given preferences by this event (it also fires upon initial page load when the preferences are first loaded), and then, on each subsequent firing of the event, compare to the previously known preferences to determine whether GA was enabled and is now disabled.

**Comment by RyanTT** [comment]
This is the event you'd need to subscribe to to implement this

https://github.com/BytexDigital/BytexDigital.Blazor.Components.CookieConsent/blob/master/BytexDigital.Blazor.Components.CookieConsent/CookieConsentService.cs#L43

**Comment by RyanTT** [comment]
Please let me know if this helps you out:

https://github.com/BytexDigital/BytexDigital.Blazor.Components.CookieConsent#stop-scripts-like-google-analytics-from-running-if-consent-is-revoked
https://www.nuget.org/packages/BytexDigital.Blazor.Components.CookieConsent/1.0.18-preview.1683580915

**Comment by leugeniam** [comment]
Hi Ryan, 
it works for me!
Thank you, it was exactly what I was searching for!

**Comment by RyanTT** [comment]
Glad it works and thanks for letting me know @leugeniam @OWGS Will push it to stable soon.
